---
title: "COVID-19 trend"
author: "RLT"
date: "11/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
owid_covid_data <- read_csv("COVID_DATA/owid-covid-data.csv")

owid=owid_covid_data
```

Variable names




```{r}
names(owid)
head(owid)
```

```{r}
library(tidyverse)
```


```{r}
owid %>% 
  filter(location=="Aruba")
  
```


```{r}
library(ggplot2)


mid <- 
  owid %>% 
  filter(location=="Aruba") %>% 
  summarize(mean=mean(new_cases, na.rm=TRUE))
mid=mid$mean
mid
owid %>% 
  filter(location=="Aruba") %>% 
ggplot(aes(date, new_cases, colour=new_cases))+
  geom_linerange(aes(x=date, ymax=new_cases, ymin=0.75))+
  scale_color_gradient2(midpoint = mid, low = "grey", mid = "blue",
                            high = "red")
  
  scale_color_gradient(low = "grey", high = "red")+
  ggtitle("Aruba: Covid-19 New Cases")
```

```{r}
library(readr)
us_counties <- read_csv("~/Google Drive/GitHub_Google_Drive/GitHub/covid-19-data-master/us-counties.csv")

#write.csv(us_counties, "COVID_DATA/us_counties.csv")
```

```{r}
us_counties %>% 
  filter(state=="Puerto Rico", county=="San Juan") %>% 
ggplot(aes(date, cases))+
  geom_count(size=1)
```

