---
title: "COVID-19 trend"
author: "RLT"
date: "11/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, packages and data}
library(tidyverse)
library(ggplot2)
library(readr)
owid_covid_data <- read_csv("COVID_DATA/owid-covid-data.csv")

owid=owid_covid_data
```

Variable names




```{r, head}
names(owid)
head(owid)
```




```{r, Aruba}
owid %>% 
  filter(location=="Aruba")%>% 
  dplyr::mutate(new_cases = replace_na(new_cases, 0))
  
```
Calucalting a rolling average , rolling mean

From this website

https://www.storybench.org/how-to-calculate-a-rolling-average-in-r/



```{r, rolling average}

Aruba=owid %>% 
  filter(location=="Aruba") %>% 
  dplyr::mutate(new_cases = replace_na(new_cases, 0)) %>% 
    dplyr::mutate(new_cases_03da = zoo::rollmean(new_cases, k = 3, fill = NA),
                  new_cases_07da = zoo::rollmean(new_cases, k = 7, fill = NA),
                  new_cases_14da = zoo::rollmean(new_cases, k = 14, fill = NA))
Aruba
```













```{r, aruba graph}
library(ggplot2)


Aruba %>% 
  summarize(mean=mean(new_cases_03da, na.rm=TRUE))
mid=mean(Aruba$new_cases_03da, na.rm=TRUE)
mid


Aruba %>% 
ggplot(aes(date, new_cases, colour=new_cases_07da))+
  geom_linerange(aes(x=date, ymax=new_cases, ymin=0.75))+
  scale_color_gradient(low = "grey", high = "red")+
    geom_line(aes(x=date, new_cases_07da), colour="black")+
  ggtitle("Aruba: Covid-19 New Cases")

```


```{r, puerto rico rolling ave}

PR=owid %>% 
  filter(location=="Puerto Rico") %>% 
  dplyr::mutate(new_cases = replace_na(new_cases, 0)) %>% 
    dplyr::mutate(new_cases_03da = zoo::rollmean(new_cases, k = 3, fill = NA),
                  new_cases_07da = zoo::rollmean(new_cases, k = 7, fill = NA),
                  new_cases_14da = zoo::rollmean(new_cases, k = 14, fill = NA))
PR

library(slider)

PR2=owid %>%
  filter(location=="Puerto Rico") %>% 
  mutate(new_cases_14daSlider = slider::slide_dbl(new_cases, mean, .before = 14, .after = 0)) %>%
  mutate(new_cases_07daSlider = slider::slide_dbl(new_cases, mean, .before = 7, .after = 0)) %>%
  mutate(new_cases_03daSlider = slider::slide_dbl(new_cases, mean, .before = 3, .after = 0)) %>%
  ungroup()
PR2
```

```{r, PR graph}
PR %>% 
ggplot(aes(date, new_cases, colour=new_cases_14da))+
  geom_linerange(aes(x=date, ymax=new_cases, ymin=0.75))+
  scale_color_gradient(low = "grey", high = "red")+
    geom_line(aes(x=date, new_cases_14da), colour="black")+
  ggtitle("Puerto Rico: Covid-19 New Cases, rolling average of 7 days")
```


```{r, slider function}

PR2 %>% 
ggplot(aes(date, new_cases, colour=new_cases_14daSlider))+
  geom_linerange(aes(x=date, ymax=new_cases, ymin=0.75))+
  scale_color_gradient(low = "black", high = "red")+
    geom_line(aes(x=date, new_cases_14daSlider), colour="black")+
 labs(colour = "Average of \nlast 14 days")+
  ggtitle("Puerto Rico: Covid-19 New Cases, \n backward rolling average of 14 days ")

ggsave("PR_COCID_14day_average.png")
#  geom_line(aes(x=date, new_cases_07daSlider), colour="blue")+
```



```{r, uscounties}
library(readr)
us_counties <- read_csv("~/Dropbox/GitHub_Google_Drive/GitHub/covid-19-data-master/us-counties.csv")

#write.csv(us_counties, "COVID_DATA/us_counties.csv")
```

```{r, PR and SJ}
us_counties %>% 
  filter(state=="Puerto Rico", county=="San Juan") %>% 
ggplot(aes(date, cases))+
  geom_count(size=1)
```

