---
title: "Calendario, Segundo semestre 2023"
output:
  html_document:
    css: tutorial.css
    fig_caption: yes
    highlight: pygments
    theme: simplex
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(huxtable)
library(knitr)
library(tidyverse)


```



Favor mirar el calendario regularmente, ya que este puede cambiar!

```{r include=FALSE}
Calendario_Curso <- read.csv("Schedule_VD_2020.csv")
library(tidyverse)
library(huxtable)
```



```{r, echo=FALSE}
huxtable(Calendario_Curso)%>%
  theme_article(header_col = FALSE)%>%
  huxtable::set_position("left") %>%
huxtable::set_bottom_border(row = 1, col = everywhere, value = 2) %>%
huxtable::set_caption("Calendario tentativo")%>%
      huxtable::set_background_color(1:1, 1:1, "cadetblue4")%>% 
      huxtable::set_background_color(1:1, 2:2, "purple")%>% 
      huxtable::set_background_color(1:1, 3:3, "chocolate4")%>% 
      huxtable::set_background_color(1:1, 4:4, "goldenrod4")%>% 
      huxtable::set_background_color(1:1, 5:5, "red")%>%
      huxtable::set_text_color(1:1, 1:5, "white")%>%
      huxtable::set_text_color(7:7, 2:2, "blue4")%>%
  huxtable::set_text_color(9:9, 2:2, "blue4")%>%
huxtable::set_text_color(11:11, 2:2, "blue4")%>%
huxtable::set_text_color(13:13, 2:2, "blue4")%>%               
  huxtable::set_text_color(15:15, 2:2, "blue4")%>%
  huxtable::set_text_color(17:17, 2:2, "blue4")%>%
  huxtable::set_text_color(19:19, 2:2, "blue4")%>%
  huxtable::set_text_color(21:21, 2:2, "blue4")%>%
huxtable::set_text_color(23:23, 2:2, "blue4")%>%
huxtable::set_text_color(25:25, 2:2, "blue4")%>%
huxtable::set_text_color(27:27, 2:2, "blue4")%>%
huxtable::set_text_color(29:29, 2:2, "blue4")%>%
huxtable::set_text_color(31:31, 2:2, "blue4")%>%
huxtable::set_text_color(33:33, 2:2, "blue4")
```


